import type { Category, Prompt } from '../types';

export const presetCategories: Category[] = [
  { id: 'development', name: '编程', description: '编程相关的提示词', icon: '💻', sort: 1, isCustom: false },
  { id: 'writing', name: '写作', description: '写作相关的提示词', icon: '✍️', sort: 2, isCustom: false },
  { id: 'translation', name: '翻译', description: '翻译相关的提示词', icon: '🌐', sort: 3, isCustom: false },
  { id: 'analysis', name: '分析', description: '数据分析相关的提示词', icon: '📊', sort: 4, isCustom: false },
  { id: 'creativity', name: '创意', description: '创意策划相关的提示词', icon: '🎨', sort: 5, isCustom: false },
  { id: 'product', name: '产品', description: '产品管理相关的提示词', icon: '📋', sort: 6, isCustom: false },
]

export const presetPrompts: Prompt[] = [
  {
    id: 'preset-1',
    category: 'development',
    title: '代码审查助手',
    description: '一个用于代码审查的详细清单和建议。',
    content: '请审查以下代码，并根据以下方面提供反馈：\n1. 可读性：代码是否易于理解？变量和函数命名是否清晰？\n2. 性能：是否存在任何潜在的性能瓶颈？\n3. 安全性：是否存在任何常见的安全漏洞（如SQL注入、XSS）？\n4. 最佳实践：代码是否遵循了语言和框架的最佳实践？\n5. 错误处理：是否充分处理了潜在的错误情况？\n\n```\n[在此处粘贴您的代码]\n```',
    tags: ['开发', '代码质量', '审查'],
    isCustom: false,
    useCount: 15,
    createTime: String(Date.now()),
    updateTime: String(Date.now()),
  },
  {
    id: 'preset-2',
    category: 'marketing',
    title: '社交媒体帖子生成器',
    description: '为不同的社交媒体平台创建引人入胜的帖子。',
    content: '请为 [产品/服务] 创建一个在 [社交媒体平台，如Instagram, Twitter, Facebook] 上发布的帖子。\n目标受众是 [目标受众]。\n帖子的基调应该是 [基调，如专业、有趣、友好]。\n请包含相关的 #标签 和一个明确的行动号召 (CTA)。',
    tags: ['营销', '社交媒体', '内容创作'],
    isCustom: false,
    useCount: 25,
    createTime: String(Date.now()),
    updateTime: String(Date.now()),
  },
  {
    id: 'preset-3',
    category: 'writing',
    title: '创意故事开头',
    description: '生成一个引人入胜的故事开头来激发创作灵感。',
    content: '请根据以下三个关键词创作一个故事的开头段落：\n1. [关键词1]\n2. [关键词2]\n3. [关键词3]\n\n故事的类型是 [故事类型，如科幻、悬疑、奇幻]。',
    tags: ['写作', '创意', '故事'],
    isCustom: false,
    useCount: 18,
    createTime: String(Date.now()),
    updateTime: String(Date.now()),
  },
  {
    id: 'preset-4',
    category: 'business',
    title: 'SWOT分析框架',
    description: '一个用于商业分析的结构化SWOT框架。',
    content: '请对 [公司/产品名称] 进行一次SWOT分析。\n- 优势 (Strengths): [内部的、积极的因素]\n- 劣势 (Weaknesses): [内部的、消极的因素]\n- 机会 (Opportunities): [外部的、积极的因素]\n- 威胁 (Threats): [外部的、消极的因素]\n\n请为每个方面提供至少3个要点。',
    tags: ['商业', '分析', '策略'],
    isCustom: false,
    useCount: 12,
    createTime: String(Date.now()),
    updateTime: String(Date.now()),
  },
  {
    id: 'preset-5',
    category: 'education',
    title: '学习计划制定器',
    description: '帮助用户为新的学习主题创建一个结构化的周学习计划。',
    content: '我想学习 [学习主题]。\n我的可用学习时间是每周 [可用小时数] 小时。\n请为我创建一个为期一周的详细学习计划，包括每天的学习目标、要涵盖的关键概念和建议的学习活动（如阅读、练习、项目）。',
    tags: ['教育', '学习', '计划'],
    isCustom: false,
    useCount: 22,
    createTime: String(Date.now()),
    updateTime: String(Date.now()),
  },
]
